"""
Detection: T1485.001 — Lifecycle-Triggered Deletion
Category: data
Severity: INFO
MITRE: T1485.001
Source: https://attack.mitre.org/techniques/T1485/001

Auto-generated by cloud-sec-blog detection pipeline.
Compatible with: https://github.com/jackiecloudsec/detection-as-code
"""

import json
import logging

log = logging.getLogger(__name__)

# Detection metadata
DETECTION_ID = "attack-T1485.001"
DETECTION_NAME = "T1485.001 — Lifecycle-Triggered Deletion"
DETECTION_SEVERITY = "info"
MITRE_TTPS = ['T1485.001']
CLOUDTRAIL_EVENTS = ['CreateBucket', 'DeleteBucket', 'DeleteConfigurationRecorder', 'DeleteDeliveryChannel', 'GetBucketAcl', 'ListBuckets', 'PutBucketAcl', 'PutBucketPolicy', 'PutBucketPublicAccessBlock', 'StopConfigurationRecorder']


def logql_query() -> str:
    """LogQL query for Loki to pull relevant CloudTrail events."""
    return '{job="cloudtrail"} |~ `"eventName":"(CreateBucket|DeleteBucket|DeleteConfigurationRecorder|DeleteDeliveryChannel|GetBucketAcl|ListBuckets|PutBucketAcl|PutBucketPolicy|PutBucketPublicAccessBlock|StopConfigurationRecorder)"`'


def detect(event: dict) -> bool:
    """
    Evaluate whether a CloudTrail event matches this detection.

    Args:
        event: parsed CloudTrail event dict

    Returns:
        True if the event should trigger an alert
    """
    try:
        event_name = event.get('eventName', '')
        return event_name in ("CreateBucket", "DeleteBucket", "DeleteConfigurationRecorder", "DeleteDeliveryChannel", "GetBucketAcl", "ListBuckets", "PutBucketAcl", "PutBucketPolicy", "PutBucketPublicAccessBlock", "StopConfigurationRecorder",)
    except Exception as e:
        log.warning(f"Detection error in {DETECTION_ID}: {e}")
        return False


def title(event: dict) -> str:
    """Generate alert title with event context."""
    user = event.get("userIdentity", {}).get("arn", "unknown")
    event_name = event.get("eventName", "unknown")
    return f"{DETECTION_NAME} — {event_name} by {user}"


def severity(event: dict) -> str:
    """Return severity level. Can be dynamic based on event context."""
    error_code = event.get("errorCode")
    if error_code:
        return "low"  # failed attempt is lower priority
    return DETECTION_SEVERITY


def runbook(event: dict) -> str:
    """Return remediation steps for responders."""
    return "1. Review the CloudTrail event in the alert context\n2. Identify the IAM principal (userIdentity.arn) and source IP\n3. Determine if the activity is authorized\n4. If unauthorized: revert bucket policy and enable Block Public Access\n5. Check for data exfiltration in S3 server access logs\n6. MITRE ATT&CK reference: T1485.001\n7. Threat intel source: https://attack.mitre.org/techniques/T1485/001"


def metadata() -> dict:
    """Return detection metadata for the engine registry."""
    return {
        "id": DETECTION_ID,
        "name": DETECTION_NAME,
        "severity": DETECTION_SEVERITY,
        "mitre_ttps": MITRE_TTPS,
        "cloudtrail_events": CLOUDTRAIL_EVENTS,
        "category": "data",
        "description": "Adversaries may modify the lifecycle policies of a cloud storage bucket to destroy all objects stored within.    Cloud storage buckets often allow users to set lifecycle policies to automate the migration, archival, or deletion of objects after a set period of time.(Citation: AWS Storage Lifecycles)",
    }
