"""
Detection: T1580 — Cloud Infrastructure Discovery
Category: data
Severity: INFO
MITRE: T1580
Source: https://attack.mitre.org/techniques/T1580

Auto-generated by cloud-sec-blog detection pipeline.
Compatible with: https://github.com/jackiecloudsec/detection-as-code
"""

import json
import logging

log = logging.getLogger(__name__)

# Detection metadata
DETECTION_ID = "attack-T1580"
DETECTION_NAME = "T1580 — Cloud Infrastructure Discovery"
DETECTION_SEVERITY = "info"
MITRE_TTPS = ['T1580']
CLOUDTRAIL_EVENTS = ['DescribeInstances', 'ListBuckets', 'DescribeDBInstances', 'ListFunctions', 'DescribeVpcs', 'DescribeSecurityGroups', 'GetAccountAuthorizationDetails', 'ListRoles', 'ListUsers']


def logql_query() -> str:
    """LogQL query for Loki to pull relevant CloudTrail events."""
    return '{job="cloudtrail"} |~ `"eventName":"(DescribeInstances|ListBuckets|DescribeDBInstances|ListFunctions|DescribeVpcs|DescribeSecurityGroups|GetAccountAuthorizationDetails|ListRoles|ListUsers)"`'


def detect(event: dict) -> bool:
    """
    Evaluate whether a CloudTrail event matches this detection.

    Args:
        event: parsed CloudTrail event dict

    Returns:
        True if the event should trigger an alert
    """
    try:
        event_name = event.get('eventName', '')
        return event_name in ("DescribeInstances", "ListBuckets", "DescribeDBInstances", "ListFunctions", "DescribeVpcs", "DescribeSecurityGroups", "GetAccountAuthorizationDetails", "ListRoles", "ListUsers",)
    except Exception as e:
        log.warning(f"Detection error in {DETECTION_ID}: {e}")
        return False


def title(event: dict) -> str:
    """Generate alert title with event context."""
    user = event.get("userIdentity", {}).get("arn", "unknown")
    event_name = event.get("eventName", "unknown")
    return f"{DETECTION_NAME} — {event_name} by {user}"


def severity(event: dict) -> str:
    """Return severity level. Can be dynamic based on event context."""
    error_code = event.get("errorCode")
    if error_code:
        return "low"  # failed attempt is lower priority
    return DETECTION_SEVERITY


def runbook(event: dict) -> str:
    """Return remediation steps for responders."""
    return "1. Review the CloudTrail event in the alert context\n2. Identify the IAM principal (userIdentity.arn) and source IP\n3. Determine if the activity is authorized\n4. If unauthorized: contain the affected resource\n5. Preserve CloudTrail logs for forensic analysis\n6. MITRE ATT&CK reference: T1580\n7. Threat intel source: https://attack.mitre.org/techniques/T1580"


def metadata() -> dict:
    """Return detection metadata for the engine registry."""
    return {
        "id": DETECTION_ID,
        "name": DETECTION_NAME,
        "severity": DETECTION_SEVERITY,
        "mitre_ttps": MITRE_TTPS,
        "cloudtrail_events": CLOUDTRAIL_EVENTS,
        "category": "data",
        "description": "An adversary may attempt to discover infrastructure and resources that are available within an infrastructure-as-a-service (IaaS) environment. This includes compute service resources such as instances, virtual machines, and snapshots as well as resources of other services including the storage and d",
    }
