"""
Detection: CVE-2026-1776
Category: data
Severity: INFO
MITRE: N/A
Source: https://nvd.nist.gov/vuln/detail/CVE-2026-1776

Auto-generated by cloud-sec-blog detection pipeline.
Compatible with: https://github.com/jackiecloudsec/detection-as-code
"""

import json
import logging

log = logging.getLogger(__name__)

# Detection metadata
DETECTION_ID = "nvd-CVE-2026-1776"
DETECTION_NAME = "CVE-2026-1776"
DETECTION_SEVERITY = "info"
MITRE_TTPS = []
CLOUDTRAIL_EVENTS = ['DeleteBucketPolicy', 'DeleteConfigurationRecorder', 'DeleteDeliveryChannel', 'DeleteObject', 'GetBucketPolicy', 'GetObject', 'ListBuckets', 'PutBucketAcl', 'PutBucketPolicy', 'PutBucketPublicAccessBlock', 'PutObject', 'StopConfigurationRecorder']


def logql_query() -> str:
    """LogQL query for Loki to pull relevant CloudTrail events."""
    return '{job="cloudtrail"} |~ `"eventName":"(DeleteBucketPolicy|DeleteConfigurationRecorder|DeleteDeliveryChannel|DeleteObject|GetBucketPolicy|GetObject|ListBuckets|PutBucketAcl|PutBucketPolicy|PutBucketPublicAccessBlock)"`'


def detect(event: dict) -> bool:
    """
    Evaluate whether a CloudTrail event matches this detection.

    Args:
        event: parsed CloudTrail event dict

    Returns:
        True if the event should trigger an alert
    """
    try:
        event_name = event.get('eventName', '')
        return event_name in ("DeleteBucketPolicy", "DeleteConfigurationRecorder", "DeleteDeliveryChannel", "DeleteObject", "GetBucketPolicy", "GetObject", "ListBuckets", "PutBucketAcl", "PutBucketPolicy", "PutBucketPublicAccessBlock",)
    except Exception as e:
        log.warning(f"Detection error in {DETECTION_ID}: {e}")
        return False


def title(event: dict) -> str:
    """Generate alert title with event context."""
    user = event.get("userIdentity", {}).get("arn", "unknown")
    event_name = event.get("eventName", "unknown")
    return f"{DETECTION_NAME} — {event_name} by {user}"


def severity(event: dict) -> str:
    """Return severity level. Can be dynamic based on event context."""
    error_code = event.get("errorCode")
    if error_code:
        return "low"  # failed attempt is lower priority
    return DETECTION_SEVERITY


def runbook(event: dict) -> str:
    """Return remediation steps for responders."""
    return "1. Review the CloudTrail event in the alert context\n2. Identify the IAM principal (userIdentity.arn) and source IP\n3. Determine if the activity is authorized\n4. If unauthorized: revert bucket policy and enable Block Public Access\n5. Check for data exfiltration in S3 server access logs\n7. Threat intel source: https://nvd.nist.gov/vuln/detail/CVE-2026-1776"


def metadata() -> dict:
    """Return detection metadata for the engine registry."""
    return {
        "id": DETECTION_ID,
        "name": DETECTION_NAME,
        "severity": DETECTION_SEVERITY,
        "mitre_ttps": MITRE_TTPS,
        "cloudtrail_events": CLOUDTRAIL_EVENTS,
        "category": "data",
        "description": "Camaleon CMS versions 2.4.5.0 through 2.9.0, prior to commit f54a77e, contain a path traversal vulnerability in the AWS S3 uploader implementation that allows authenticated users to read arbitrary files from the web server’s filesystem. The issue occurs in the download_private_file functionality whe",
    }
