"""
Detection: Need to process 1000 files in AWS. Looking for guidance.
Category: data
Severity: INFO
MITRE: N/A
Source: https://www.reddit.com/r/aws/comments/1rs3zdq/need_to_process_1000_files_in_aws_looking_for/

Auto-generated by cloud-sec-blog detection pipeline.
Compatible with: https://github.com/jackiecloudsec/detection-as-code
"""

import json
import logging

log = logging.getLogger(__name__)

# Detection metadata
DETECTION_ID = "reddit-1rs3zdq"
DETECTION_NAME = "Need to process 1000 files in AWS. Looking for guidance."
DETECTION_SEVERITY = "info"
MITRE_TTPS = []
CLOUDTRAIL_EVENTS = ['AddPermission', 'CreateFunction', 'DeleteBucketPolicy', 'DeleteObject', 'GetBucketPolicy', 'GetObject', 'InvokeFunction', 'ListBuckets', 'PutBucketAcl', 'PutBucketPolicy', 'PutBucketPublicAccessBlock', 'PutObject', 'UpdateFunctionCode', 'UpdateFunctionConfiguration']


def logql_query() -> str:
    """LogQL query for Loki to pull relevant CloudTrail events."""
    return '{job="cloudtrail"} |~ `"eventName":"(AddPermission|CreateFunction|DeleteBucketPolicy|DeleteObject|GetBucketPolicy|GetObject|InvokeFunction|ListBuckets|PutBucketAcl|PutBucketPolicy)"`'


def detect(event: dict) -> bool:
    """
    Evaluate whether a CloudTrail event matches this detection.

    Args:
        event: parsed CloudTrail event dict

    Returns:
        True if the event should trigger an alert
    """
    try:
        event_name = event.get('eventName', '')
        return event_name in ("AddPermission", "CreateFunction", "DeleteBucketPolicy", "DeleteObject", "GetBucketPolicy", "GetObject", "InvokeFunction", "ListBuckets", "PutBucketAcl", "PutBucketPolicy",)
    except Exception as e:
        log.warning(f"Detection error in {DETECTION_ID}: {e}")
        return False


def title(event: dict) -> str:
    """Generate alert title with event context."""
    user = event.get("userIdentity", {}).get("arn", "unknown")
    event_name = event.get("eventName", "unknown")
    return f"{DETECTION_NAME} — {event_name} by {user}"


def severity(event: dict) -> str:
    """Return severity level. Can be dynamic based on event context."""
    error_code = event.get("errorCode")
    if error_code:
        return "low"  # failed attempt is lower priority
    return DETECTION_SEVERITY


def runbook(event: dict) -> str:
    """Return remediation steps for responders."""
    return "1. Review the CloudTrail event in the alert context\n2. Identify the IAM principal (userIdentity.arn) and source IP\n3. Determine if the activity is authorized\n4. If unauthorized: revert bucket policy and enable Block Public Access\n5. Check for data exfiltration in S3 server access logs\n7. Threat intel source: https://www.reddit.com/r/aws/comments/1rs3zdq/need_to_process_1000_files_in_aws_looking_for/"


def metadata() -> dict:
    """Return detection metadata for the engine registry."""
    return {
        "id": DETECTION_ID,
        "name": DETECTION_NAME,
        "severity": DETECTION_SEVERITY,
        "mitre_ttps": MITRE_TTPS,
        "cloudtrail_events": CLOUDTRAIL_EVENTS,
        "category": "data",
        "description": "I'm building a document extraction pipeline on AWS for a client. PDFs go into S3, which triggers a Lambda chain: PDF concatenation -&gt; text extraction (Textract + Bedrock VLM fallback) -&gt; PII redaction (Comprehend) -&gt; structured LLM extraction (Gemini via Fargate). Currently working with \~1",
    }
