"""
Detection: AWS S3 adds support for regional namespace
Category: data
Severity: INFO
MITRE: N/A
Source: https://www.reddit.com/r/aws/comments/1rsopjc/aws_s3_adds_support_for_regional_namespace/

Auto-generated by cloud-sec-blog detection pipeline.
Compatible with: https://github.com/jackiecloudsec/detection-as-code
"""

import json
import logging

log = logging.getLogger(__name__)

# Detection metadata
DETECTION_ID = "reddit-1rsopjc"
DETECTION_NAME = "AWS S3 adds support for regional namespace"
DETECTION_SEVERITY = "info"
MITRE_TTPS = []
CLOUDTRAIL_EVENTS = ['CreateBucket', 'DeleteBucket', 'DeleteBucketPolicy', 'DeleteObject', 'GetBucketAcl', 'GetBucketPolicy', 'GetObject', 'ListBuckets', 'PutBucketAcl', 'PutBucketPolicy', 'PutBucketPublicAccessBlock', 'PutObject']


def logql_query() -> str:
    """LogQL query for Loki to pull relevant CloudTrail events."""
    return '{job="cloudtrail"} |~ `"eventName":"(CreateBucket|DeleteBucket|DeleteBucketPolicy|DeleteObject|GetBucketAcl|GetBucketPolicy|GetObject|ListBuckets|PutBucketAcl|PutBucketPolicy)"`'


def detect(event: dict) -> bool:
    """
    Evaluate whether a CloudTrail event matches this detection.

    Args:
        event: parsed CloudTrail event dict

    Returns:
        True if the event should trigger an alert
    """
    try:
        event_name = event.get('eventName', '')
        return event_name in ("CreateBucket", "DeleteBucket", "DeleteBucketPolicy", "DeleteObject", "GetBucketAcl", "GetBucketPolicy", "GetObject", "ListBuckets", "PutBucketAcl", "PutBucketPolicy",)
    except Exception as e:
        log.warning(f"Detection error in {DETECTION_ID}: {e}")
        return False


def title(event: dict) -> str:
    """Generate alert title with event context."""
    user = event.get("userIdentity", {}).get("arn", "unknown")
    event_name = event.get("eventName", "unknown")
    return f"{DETECTION_NAME} — {event_name} by {user}"


def severity(event: dict) -> str:
    """Return severity level. Can be dynamic based on event context."""
    error_code = event.get("errorCode")
    if error_code:
        return "low"  # failed attempt is lower priority
    return DETECTION_SEVERITY


def runbook(event: dict) -> str:
    """Return remediation steps for responders."""
    return "1. Review the CloudTrail event in the alert context\n2. Identify the IAM principal (userIdentity.arn) and source IP\n3. Determine if the activity is authorized\n4. If unauthorized: revert bucket policy and enable Block Public Access\n5. Check for data exfiltration in S3 server access logs\n7. Threat intel source: https://www.reddit.com/r/aws/comments/1rsopjc/aws_s3_adds_support_for_regional_namespace/"


def metadata() -> dict:
    """Return detection metadata for the engine registry."""
    return {
        "id": DETECTION_ID,
        "name": DETECTION_NAME,
        "severity": DETECTION_SEVERITY,
        "mitre_ttps": MITRE_TTPS,
        "cloudtrail_events": CLOUDTRAIL_EVENTS,
        "category": "data",
        "description": "[https://aws.amazon.com/about-aws/whats-new/2026/03/amazon-s3-account-regional-namespaces/](https://aws.amazon.com/about-aws/whats-new/2026/03/amazon-s3-account-regional-namespaces/)  This can help prevent squatting of S3 bucket names. As many are probably already aware, AWS bucket name needs to be",
    }
