"""
Detection: Why is there no cheap options for relational databases on AWS?
Category: cloudtrail
Severity: INFO
MITRE: N/A
Source: https://www.reddit.com/r/aws/comments/1rs5zub/why_is_there_no_cheap_options_for_relational/

Auto-generated by cloud-sec-blog detection pipeline.
Compatible with: https://github.com/jackiecloudsec/detection-as-code
"""

import json
import logging

log = logging.getLogger(__name__)

# Detection metadata
DETECTION_ID = "reddit-1rs5zub"
DETECTION_NAME = "Why is there no cheap options for relational databases on AWS?"
DETECTION_SEVERITY = "info"
MITRE_TTPS = []
CLOUDTRAIL_EVENTS = ['CreateDBInstance', 'CreateDBSnapshot', 'DescribeDBInstances', 'ModifyDBInstance', 'RestoreDBInstanceFromDBSnapshot']


def logql_query() -> str:
    """LogQL query for Loki to pull relevant CloudTrail events."""
    return '{job="cloudtrail"} |~ `"eventName":"(CreateDBInstance|CreateDBSnapshot|DescribeDBInstances|ModifyDBInstance|RestoreDBInstanceFromDBSnapshot)"`'


def detect(event: dict) -> bool:
    """
    Evaluate whether a CloudTrail event matches this detection.

    Args:
        event: parsed CloudTrail event dict

    Returns:
        True if the event should trigger an alert
    """
    try:
        event_name = event.get('eventName', '')
        return event_name in ("CreateDBInstance", "CreateDBSnapshot", "DescribeDBInstances", "ModifyDBInstance", "RestoreDBInstanceFromDBSnapshot",)
    except Exception as e:
        log.warning(f"Detection error in {DETECTION_ID}: {e}")
        return False


def title(event: dict) -> str:
    """Generate alert title with event context."""
    user = event.get("userIdentity", {}).get("arn", "unknown")
    event_name = event.get("eventName", "unknown")
    return f"{DETECTION_NAME} — {event_name} by {user}"


def severity(event: dict) -> str:
    """Return severity level. Can be dynamic based on event context."""
    error_code = event.get("errorCode")
    if error_code:
        return "low"  # failed attempt is lower priority
    return DETECTION_SEVERITY


def runbook(event: dict) -> str:
    """Return remediation steps for responders."""
    return "1. Review the CloudTrail event in the alert context\n2. Identify the IAM principal (userIdentity.arn) and source IP\n3. Determine if the activity is authorized\n4. If unauthorized: contain the affected resource\n5. Preserve CloudTrail logs for forensic analysis\n7. Threat intel source: https://www.reddit.com/r/aws/comments/1rs5zub/why_is_there_no_cheap_options_for_relational/"


def metadata() -> dict:
    """Return detection metadata for the engine registry."""
    return {
        "id": DETECTION_ID,
        "name": DETECTION_NAME,
        "severity": DETECTION_SEVERITY,
        "mitre_ttps": MITRE_TTPS,
        "cloudtrail_events": CLOUDTRAIL_EVENTS,
        "category": "cloudtrail",
        "description": "It always made me wonder why even the cheapest RDS DB would be $10+ per month and 20 GB minimum. Why doesn't AWS offer some really lightweight DB options for small apps?",
    }
