"""
Detection: Vendor risk assessment found 60+ third-party integrations with persistent API ac
Category: cloudtrail
Severity: INFO
MITRE: N/A
Source: https://www.reddit.com/r/AskNetsec/comments/1rsgmul/vendor_risk_assessment_found_60_thirdparty/

Auto-generated by cloud-sec-blog detection pipeline.
Compatible with: https://github.com/jackiecloudsec/detection-as-code
"""

import json
import logging

log = logging.getLogger(__name__)

# Detection metadata
DETECTION_ID = "reddit-1rsgmul"
DETECTION_NAME = "Vendor risk assessment found 60+ third-party integrations with persistent API ac"
DETECTION_SEVERITY = "info"
MITRE_TTPS = []
CLOUDTRAIL_EVENTS = ['GetParameter', 'GetParameters', 'PutParameter', 'SendCommand', 'StartSession']


def logql_query() -> str:
    """LogQL query for Loki to pull relevant CloudTrail events."""
    return '{job="cloudtrail"} |~ `"eventName":"(GetParameter|GetParameters|PutParameter|SendCommand|StartSession)"`'


def detect(event: dict) -> bool:
    """
    Evaluate whether a CloudTrail event matches this detection.

    Args:
        event: parsed CloudTrail event dict

    Returns:
        True if the event should trigger an alert
    """
    try:
        event_name = event.get('eventName', '')
        return event_name in ("GetParameter", "GetParameters", "PutParameter", "SendCommand", "StartSession",)
    except Exception as e:
        log.warning(f"Detection error in {DETECTION_ID}: {e}")
        return False


def title(event: dict) -> str:
    """Generate alert title with event context."""
    user = event.get("userIdentity", {}).get("arn", "unknown")
    event_name = event.get("eventName", "unknown")
    return f"{DETECTION_NAME} — {event_name} by {user}"


def severity(event: dict) -> str:
    """Return severity level. Can be dynamic based on event context."""
    error_code = event.get("errorCode")
    if error_code:
        return "low"  # failed attempt is lower priority
    return DETECTION_SEVERITY


def runbook(event: dict) -> str:
    """Return remediation steps for responders."""
    return "1. Review the CloudTrail event in the alert context\n2. Identify the IAM principal (userIdentity.arn) and source IP\n3. Determine if the activity is authorized\n4. If unauthorized: contain the affected resource\n5. Preserve CloudTrail logs for forensic analysis\n7. Threat intel source: https://www.reddit.com/r/AskNetsec/comments/1rsgmul/vendor_risk_assessment_found_60_thirdparty/"


def metadata() -> dict:
    """Return detection metadata for the engine registry."""
    return {
        "id": DETECTION_ID,
        "name": DETECTION_NAME,
        "severity": DETECTION_SEVERITY,
        "mitre_ttps": MITRE_TTPS,
        "cloudtrail_events": CLOUDTRAIL_EVENTS,
        "category": "cloudtrail",
        "description": "Running through vendor risk questionnaire for insurance renewal. One question asked how many third parties have technical integration to our systems. Estimated maybe 15. Started actually inventorying and the number is over 60.  Found Zapier workflows connecting our CRM to random apps. Webhook endpoi",
    }
