"""
Detection: Migrating from Ansible to AWS SSM for Windows fleet across multiple accounts – h
Category: cloudtrail
Severity: INFO
MITRE: N/A
Source: https://www.reddit.com/r/aws/comments/1rrhmrl/migrating_from_ansible_to_aws_ssm_for_windows/

Auto-generated by cloud-sec-blog detection pipeline.
Compatible with: https://github.com/jackiecloudsec/detection-as-code
"""

import json
import logging

log = logging.getLogger(__name__)

# Detection metadata
DETECTION_ID = "reddit-1rrhmrl"
DETECTION_NAME = "Migrating from Ansible to AWS SSM for Windows fleet across multiple accounts – h"
DETECTION_SEVERITY = "info"
MITRE_TTPS = []
CLOUDTRAIL_EVENTS = ['DeleteConfigurationRecorder', 'DeleteDeliveryChannel', 'GetParameter', 'GetParameters', 'PutParameter', 'SendCommand', 'StartSession', 'StopConfigurationRecorder']


def logql_query() -> str:
    """LogQL query for Loki to pull relevant CloudTrail events."""
    return '{job="cloudtrail"} |~ `"eventName":"(DeleteConfigurationRecorder|DeleteDeliveryChannel|GetParameter|GetParameters|PutParameter|SendCommand|StartSession|StopConfigurationRecorder)"`'


def detect(event: dict) -> bool:
    """
    Evaluate whether a CloudTrail event matches this detection.

    Args:
        event: parsed CloudTrail event dict

    Returns:
        True if the event should trigger an alert
    """
    try:
        event_name = event.get('eventName', '')
        return event_name in ("DeleteConfigurationRecorder", "DeleteDeliveryChannel", "GetParameter", "GetParameters", "PutParameter", "SendCommand", "StartSession", "StopConfigurationRecorder",)
    except Exception as e:
        log.warning(f"Detection error in {DETECTION_ID}: {e}")
        return False


def title(event: dict) -> str:
    """Generate alert title with event context."""
    user = event.get("userIdentity", {}).get("arn", "unknown")
    event_name = event.get("eventName", "unknown")
    return f"{DETECTION_NAME} — {event_name} by {user}"


def severity(event: dict) -> str:
    """Return severity level. Can be dynamic based on event context."""
    error_code = event.get("errorCode")
    if error_code:
        return "low"  # failed attempt is lower priority
    return DETECTION_SEVERITY


def runbook(event: dict) -> str:
    """Return remediation steps for responders."""
    return "1. Review the CloudTrail event in the alert context\n2. Identify the IAM principal (userIdentity.arn) and source IP\n3. Determine if the activity is authorized\n4. If unauthorized: contain the affected resource\n5. Preserve CloudTrail logs for forensic analysis\n7. Threat intel source: https://www.reddit.com/r/aws/comments/1rrhmrl/migrating_from_ansible_to_aws_ssm_for_windows/"


def metadata() -> dict:
    """Return detection metadata for the engine registry."""
    return {
        "id": DETECTION_ID,
        "name": DETECTION_NAME,
        "severity": DETECTION_SEVERITY,
        "mitre_ttps": MITRE_TTPS,
        "cloudtrail_events": CLOUDTRAIL_EVENTS,
        "category": "cloudtrail",
        "description": "Hi everyone,  I’m curious if anyone here has done a migration from Ansible to AWS Systems Manager (SSM) for configuration management, especially for a Windows-heavy fleet across multiple AWS accounts.  Our current setup uses Ansible with a fairly complex inventory structure. We rely on things like:",
    }
