"""
Detection: AWS Weekly Roundup: OpenAI partnership, AWS Elemental Inference, Strands Labs, a
Category: cloudtrail
Severity: INFO
MITRE: N/A
Source: https://aws.amazon.com/blogs/aws/aws-weekly-roundup-openai-partnership-aws-elemental-inference-strands-labs-and-more-march-2-2026/

Auto-generated by cloud-sec-blog detection pipeline.
Compatible with: https://github.com/jackiecloudsec/detection-as-code
"""

import json
import logging

log = logging.getLogger(__name__)

# Detection metadata
DETECTION_ID = "rss-awsnewsblog-aws-weekly-roundup-openai-partnership-aws-elemental-inferenc"
DETECTION_NAME = "AWS Weekly Roundup: OpenAI partnership, AWS Elemental Inference, Strands Labs, a"
DETECTION_SEVERITY = "info"
MITRE_TTPS = []
CLOUDTRAIL_EVENTS = ['CreateAccount', 'InviteAccountToOrganization', 'LeaveOrganization']


def logql_query() -> str:
    """LogQL query for Loki to pull relevant CloudTrail events."""
    return '{job="cloudtrail"} |~ `"eventName":"(CreateAccount|InviteAccountToOrganization|LeaveOrganization)"`'


def detect(event: dict) -> bool:
    """
    Evaluate whether a CloudTrail event matches this detection.

    Args:
        event: parsed CloudTrail event dict

    Returns:
        True if the event should trigger an alert
    """
    try:
        event_name = event.get('eventName', '')
        return event_name in ("CreateAccount", "InviteAccountToOrganization", "LeaveOrganization",)
    except Exception as e:
        log.warning(f"Detection error in {DETECTION_ID}: {e}")
        return False


def title(event: dict) -> str:
    """Generate alert title with event context."""
    user = event.get("userIdentity", {}).get("arn", "unknown")
    event_name = event.get("eventName", "unknown")
    return f"{DETECTION_NAME} — {event_name} by {user}"


def severity(event: dict) -> str:
    """Return severity level. Can be dynamic based on event context."""
    error_code = event.get("errorCode")
    if error_code:
        return "low"  # failed attempt is lower priority
    return DETECTION_SEVERITY


def runbook(event: dict) -> str:
    """Return remediation steps for responders."""
    return "1. Review the CloudTrail event in the alert context\n2. Identify the IAM principal (userIdentity.arn) and source IP\n3. Determine if the activity is authorized\n4. If unauthorized: contain the affected resource\n5. Preserve CloudTrail logs for forensic analysis\n7. Threat intel source: https://aws.amazon.com/blogs/aws/aws-weekly-roundup-openai-partnership-aws-elemental-inference-strands-labs-and-more-march-2-2026/"


def metadata() -> dict:
    """Return detection metadata for the engine registry."""
    return {
        "id": DETECTION_ID,
        "name": DETECTION_NAME,
        "severity": DETECTION_SEVERITY,
        "mitre_ttps": MITRE_TTPS,
        "cloudtrail_events": CLOUDTRAIL_EVENTS,
        "category": "cloudtrail",
        "description": "This past week, I’ve been deep in the trenches helping customers transform their businesses through AI-DLC (AI-Driven Lifecycle) workshops. Throughout 2026, I’ve had the privilege of facilitating these sessions for numerous customers, guiding them through a structured framework that helps organizati",
    }
