"""
Detection: Command Your Cloud at Mach Speed: Find Orca Security at RSAC 2026
Category: cloudtrail
Severity: INFO
MITRE: N/A
Source: https://orca.security/resources/blog/orca-security-rsac-2026/

Auto-generated by cloud-sec-blog detection pipeline.
Compatible with: https://github.com/jackiecloudsec/detection-as-code
"""

import json
import logging

log = logging.getLogger(__name__)

# Detection metadata
DETECTION_ID = "rss-orcasecurity-command-your-cloud-at-mach-speed-find-orca-security-at-rsac"
DETECTION_NAME = "Command Your Cloud at Mach Speed: Find Orca Security at RSAC 2026"
DETECTION_SEVERITY = "info"
MITRE_TTPS = []
CLOUDTRAIL_EVENTS = ['CreateCluster', 'CreateNodegroup', 'UpdateClusterConfig']


def logql_query() -> str:
    """LogQL query for Loki to pull relevant CloudTrail events."""
    return '{job="cloudtrail"} |~ `"eventName":"(CreateCluster|CreateNodegroup|UpdateClusterConfig)"`'


def detect(event: dict) -> bool:
    """
    Evaluate whether a CloudTrail event matches this detection.

    Args:
        event: parsed CloudTrail event dict

    Returns:
        True if the event should trigger an alert
    """
    try:
        event_name = event.get('eventName', '')
        return event_name in ("CreateCluster", "CreateNodegroup", "UpdateClusterConfig",)
    except Exception as e:
        log.warning(f"Detection error in {DETECTION_ID}: {e}")
        return False


def title(event: dict) -> str:
    """Generate alert title with event context."""
    user = event.get("userIdentity", {}).get("arn", "unknown")
    event_name = event.get("eventName", "unknown")
    return f"{DETECTION_NAME} — {event_name} by {user}"


def severity(event: dict) -> str:
    """Return severity level. Can be dynamic based on event context."""
    error_code = event.get("errorCode")
    if error_code:
        return "low"  # failed attempt is lower priority
    return DETECTION_SEVERITY


def runbook(event: dict) -> str:
    """Return remediation steps for responders."""
    return "1. Review the CloudTrail event in the alert context\n2. Identify the IAM principal (userIdentity.arn) and source IP\n3. Determine if the activity is authorized\n4. If unauthorized: contain the affected resource\n5. Preserve CloudTrail logs for forensic analysis\n7. Threat intel source: https://orca.security/resources/blog/orca-security-rsac-2026/"


def metadata() -> dict:
    """Return detection metadata for the engine registry."""
    return {
        "id": DETECTION_ID,
        "name": DETECTION_NAME,
        "severity": DETECTION_SEVERITY,
        "mitre_ttps": MITRE_TTPS,
        "cloudtrail_events": CLOUDTRAIL_EVENTS,
        "category": "cloudtrail",
        "description": "RSAC is one of our favorite weeks of the year. A chance to get off Zoom, get into the same room, and have the kinds of conversations that actually move the needle on cloud security. This year, we&#8217;re heading to San Francisco at mach speed with a packed agenda and a lot of energy. Whether [&#823",
    }
