"""
Detection: T1621 — Multi-Factor Authentication Request Generation
Category: auth
Severity: INFO
MITRE: T1621
Source: https://attack.mitre.org/techniques/T1621

Auto-generated by cloud-sec-blog detection pipeline.
Compatible with: https://github.com/jackiecloudsec/detection-as-code
"""

import json
import logging

log = logging.getLogger(__name__)

# Detection metadata
DETECTION_ID = "attack-T1621"
DETECTION_NAME = "T1621 — Multi-Factor Authentication Request Generation"
DETECTION_SEVERITY = "info"
MITRE_TTPS = ['T1621']
CLOUDTRAIL_EVENTS = ['AssumeRole', 'AssumeRoleWithSAML', 'ConsoleLogin', 'CreateAccessKey', 'CreateVirtualMFADevice', 'DeactivateMFADevice', 'DeleteVirtualMFADevice', 'EnableMFADevice', 'GetCallerIdentity', 'GetFederationToken', 'GetSecretValue']


def logql_query() -> str:
    """LogQL query for Loki to pull relevant CloudTrail events."""
    return '{job="cloudtrail"} |~ `"eventName":"(AssumeRole|AssumeRoleWithSAML|ConsoleLogin|CreateAccessKey|CreateVirtualMFADevice|DeactivateMFADevice|DeleteVirtualMFADevice|EnableMFADevice|GetCallerIdentity|GetFederationToken)"`'


def detect(event: dict) -> bool:
    """
    Evaluate whether a CloudTrail event matches this detection.

    Args:
        event: parsed CloudTrail event dict

    Returns:
        True if the event should trigger an alert
    """
    try:
        event_name = event.get('eventName', '')
        return event_name in ("AssumeRole", "AssumeRoleWithSAML", "ConsoleLogin", "CreateAccessKey", "CreateVirtualMFADevice", "DeactivateMFADevice", "DeleteVirtualMFADevice", "EnableMFADevice", "GetCallerIdentity", "GetFederationToken",)
    except Exception as e:
        log.warning(f"Detection error in {DETECTION_ID}: {e}")
        return False


def title(event: dict) -> str:
    """Generate alert title with event context."""
    user = event.get("userIdentity", {}).get("arn", "unknown")
    event_name = event.get("eventName", "unknown")
    return f"{DETECTION_NAME} — {event_name} by {user}"


def severity(event: dict) -> str:
    """Return severity level. Can be dynamic based on event context."""
    error_code = event.get("errorCode")
    if error_code:
        return "low"  # failed attempt is lower priority
    return DETECTION_SEVERITY


def runbook(event: dict) -> str:
    """Return remediation steps for responders."""
    return "1. Review the CloudTrail event in the alert context\n2. Identify the IAM principal (userIdentity.arn) and source IP\n3. Determine if the activity is authorized\n4. If unauthorized: disable the IAM user/key immediately\n5. Rotate any exposed credentials\n6. MITRE ATT&CK reference: T1621\n7. Threat intel source: https://attack.mitre.org/techniques/T1621"


def metadata() -> dict:
    """Return detection metadata for the engine registry."""
    return {
        "id": DETECTION_ID,
        "name": DETECTION_NAME,
        "severity": DETECTION_SEVERITY,
        "mitre_ttps": MITRE_TTPS,
        "cloudtrail_events": CLOUDTRAIL_EVENTS,
        "category": "auth",
        "description": "Adversaries may attempt to bypass multi-factor authentication (MFA) mechanisms and gain access to accounts by generating MFA requests sent to users.  Adversaries in possession of credentials to [Valid Accounts](https://attack.mitre.org/techniques/T1078) may be unable to complete the login process if",
    }
