"""
Detection: T1538 — Cloud Service Dashboard
Category: auth
Severity: INFO
MITRE: T1538
Source: https://attack.mitre.org/techniques/T1538

Auto-generated by cloud-sec-blog detection pipeline.
Compatible with: https://github.com/jackiecloudsec/detection-as-code
"""

import json
import logging

log = logging.getLogger(__name__)

# Detection metadata
DETECTION_ID = "attack-T1538"
DETECTION_NAME = "T1538 — Cloud Service Dashboard"
DETECTION_SEVERITY = "info"
MITRE_TTPS = ['T1538']
CLOUDTRAIL_EVENTS = ['ConsoleLogin', 'CreateAccessKey', 'DeleteConfigurationRecorder', 'DeleteDeliveryChannel', 'GetFederationToken', 'GetSecretValue', 'StopConfigurationRecorder']


def logql_query() -> str:
    """LogQL query for Loki to pull relevant CloudTrail events."""
    return '{job="cloudtrail"} |~ `"eventName":"(ConsoleLogin|CreateAccessKey|DeleteConfigurationRecorder|DeleteDeliveryChannel|GetFederationToken|GetSecretValue|StopConfigurationRecorder)"`'


def detect(event: dict) -> bool:
    """
    Evaluate whether a CloudTrail event matches this detection.

    Args:
        event: parsed CloudTrail event dict

    Returns:
        True if the event should trigger an alert
    """
    try:
        event_name = event.get('eventName', '')
        return event_name in ("ConsoleLogin", "CreateAccessKey", "DeleteConfigurationRecorder", "DeleteDeliveryChannel", "GetFederationToken", "GetSecretValue", "StopConfigurationRecorder",)
    except Exception as e:
        log.warning(f"Detection error in {DETECTION_ID}: {e}")
        return False


def title(event: dict) -> str:
    """Generate alert title with event context."""
    user = event.get("userIdentity", {}).get("arn", "unknown")
    event_name = event.get("eventName", "unknown")
    return f"{DETECTION_NAME} — {event_name} by {user}"


def severity(event: dict) -> str:
    """Return severity level. Can be dynamic based on event context."""
    error_code = event.get("errorCode")
    if error_code:
        return "low"  # failed attempt is lower priority
    return DETECTION_SEVERITY


def runbook(event: dict) -> str:
    """Return remediation steps for responders."""
    return "1. Review the CloudTrail event in the alert context\n2. Identify the IAM principal (userIdentity.arn) and source IP\n3. Determine if the activity is authorized\n4. If unauthorized: disable the IAM user/key immediately\n5. Rotate any exposed credentials\n6. MITRE ATT&CK reference: T1538\n7. Threat intel source: https://attack.mitre.org/techniques/T1538"


def metadata() -> dict:
    """Return detection metadata for the engine registry."""
    return {
        "id": DETECTION_ID,
        "name": DETECTION_NAME,
        "severity": DETECTION_SEVERITY,
        "mitre_ttps": MITRE_TTPS,
        "cloudtrail_events": CLOUDTRAIL_EVENTS,
        "category": "auth",
        "description": "An adversary may use a cloud service dashboard GUI with stolen credentials to gain useful information from an operational cloud environment, such as specific services, resources, and features. For example, the GCP Command Center can be used to view all assets, review findings of potential security r",
    }
