"""
Detection: T1211 — Exploitation for Defense Evasion
Category: auth
Severity: INFO
MITRE: T1211
Source: https://attack.mitre.org/techniques/T1211

Auto-generated by cloud-sec-blog detection pipeline.
Compatible with: https://github.com/jackiecloudsec/detection-as-code
"""

import json
import logging

log = logging.getLogger(__name__)

# Detection metadata
DETECTION_ID = "attack-T1211"
DETECTION_NAME = "T1211 — Exploitation for Defense Evasion"
DETECTION_SEVERITY = "info"
MITRE_TTPS = ['T1211']
CLOUDTRAIL_EVENTS = ['AssumeRole', 'AssumeRoleWithSAML', 'DeleteDetector', 'DeleteTrail', 'DescribeDBInstances', 'DescribeInstances', 'DescribeVpcs', 'GetCallerIdentity', 'GetFederationToken', 'ListBuckets', 'ListFunctions', 'StopLogging', 'UpdateDetector', 'UpdateTrail']


def logql_query() -> str:
    """LogQL query for Loki to pull relevant CloudTrail events."""
    return '{job="cloudtrail"} |~ `"eventName":"(AssumeRole|AssumeRoleWithSAML|DeleteDetector|DeleteTrail|DescribeDBInstances|DescribeInstances|DescribeVpcs|GetCallerIdentity|GetFederationToken|ListBuckets)"`'


def detect(event: dict) -> bool:
    """
    Evaluate whether a CloudTrail event matches this detection.

    Args:
        event: parsed CloudTrail event dict

    Returns:
        True if the event should trigger an alert
    """
    try:
        event_name = event.get('eventName', '')
        return event_name in ("AssumeRole", "AssumeRoleWithSAML", "DeleteDetector", "DeleteTrail", "DescribeDBInstances", "DescribeInstances", "DescribeVpcs", "GetCallerIdentity", "GetFederationToken", "ListBuckets",)
    except Exception as e:
        log.warning(f"Detection error in {DETECTION_ID}: {e}")
        return False


def title(event: dict) -> str:
    """Generate alert title with event context."""
    user = event.get("userIdentity", {}).get("arn", "unknown")
    event_name = event.get("eventName", "unknown")
    return f"{DETECTION_NAME} — {event_name} by {user}"


def severity(event: dict) -> str:
    """Return severity level. Can be dynamic based on event context."""
    error_code = event.get("errorCode")
    if error_code:
        return "low"  # failed attempt is lower priority
    return DETECTION_SEVERITY


def runbook(event: dict) -> str:
    """Return remediation steps for responders."""
    return "1. Review the CloudTrail event in the alert context\n2. Identify the IAM principal (userIdentity.arn) and source IP\n3. Determine if the activity is authorized\n4. Re-enable CloudTrail logging immediately\n5. This is a high-priority evasion indicator — escalate\n6. MITRE ATT&CK reference: T1211\n7. Threat intel source: https://attack.mitre.org/techniques/T1211"


def metadata() -> dict:
    """Return detection metadata for the engine registry."""
    return {
        "id": DETECTION_ID,
        "name": DETECTION_NAME,
        "severity": DETECTION_SEVERITY,
        "mitre_ttps": MITRE_TTPS,
        "cloudtrail_events": CLOUDTRAIL_EVENTS,
        "category": "auth",
        "description": "Adversaries may exploit a system or application vulnerability to bypass security features. Exploitation of a vulnerability occurs when an adversary takes advantage of a programming error in a program, service, or within the operating system software or kernel itself to execute adversary-controlled c",
    }
