"""
Detection: CVE-2026-30240
Category: auth
Severity: CRITICAL
MITRE: N/A
Source: https://nvd.nist.gov/vuln/detail/CVE-2026-30240

Auto-generated by cloud-sec-blog detection pipeline.
Compatible with: https://github.com/jackiecloudsec/detection-as-code
"""

import json
import logging

log = logging.getLogger(__name__)

# Detection metadata
DETECTION_ID = "nvd-CVE-2026-30240"
DETECTION_NAME = "CVE-2026-30240"
DETECTION_SEVERITY = "critical"
MITRE_TTPS = []
CLOUDTRAIL_EVENTS = ['BatchDeleteImage', 'ConsoleLogin', 'CreateAccessKey', 'CreateDBInstance', 'CreateRepository', 'Decrypt', 'DescribeDBInstances', 'DisableKey', 'GetAuthorizationToken', 'GetFederationToken', 'GetSecretValue', 'ModifyDBInstance', 'PutImage', 'ScheduleKeyDeletion']


def logql_query() -> str:
    """LogQL query for Loki to pull relevant CloudTrail events."""
    return '{job="cloudtrail"} |~ `"eventName":"(BatchDeleteImage|ConsoleLogin|CreateAccessKey|CreateDBInstance|CreateRepository|Decrypt|DescribeDBInstances|DisableKey|GetAuthorizationToken|GetFederationToken)"`'


def detect(event: dict) -> bool:
    """
    Evaluate whether a CloudTrail event matches this detection.

    Args:
        event: parsed CloudTrail event dict

    Returns:
        True if the event should trigger an alert
    """
    try:
        event_name = event.get('eventName', '')
        return event_name in ("BatchDeleteImage", "ConsoleLogin", "CreateAccessKey", "CreateDBInstance", "CreateRepository", "Decrypt", "DescribeDBInstances", "DisableKey", "GetAuthorizationToken", "GetFederationToken",)
    except Exception as e:
        log.warning(f"Detection error in {DETECTION_ID}: {e}")
        return False


def title(event: dict) -> str:
    """Generate alert title with event context."""
    user = event.get("userIdentity", {}).get("arn", "unknown")
    event_name = event.get("eventName", "unknown")
    return f"{DETECTION_NAME} — {event_name} by {user}"


def severity(event: dict) -> str:
    """Return severity level. Can be dynamic based on event context."""
    error_code = event.get("errorCode")
    if error_code:
        return "low"  # failed attempt is lower priority
    return DETECTION_SEVERITY


def runbook(event: dict) -> str:
    """Return remediation steps for responders."""
    return "1. Review the CloudTrail event in the alert context\n2. Identify the IAM principal (userIdentity.arn) and source IP\n3. Determine if the activity is authorized\n4. If unauthorized: disable the IAM user/key immediately\n5. Rotate any exposed credentials\n7. Threat intel source: https://nvd.nist.gov/vuln/detail/CVE-2026-30240"


def metadata() -> dict:
    """Return detection metadata for the engine registry."""
    return {
        "id": DETECTION_ID,
        "name": DETECTION_NAME,
        "severity": DETECTION_SEVERITY,
        "mitre_ttps": MITRE_TTPS,
        "cloudtrail_events": CLOUDTRAIL_EVENTS,
        "category": "auth",
        "description": "Budibase is a low code platform for creating internal tools, workflows, and admin panels. In 3.31.5 and earlier, a path traversal vulnerability in the PWA (Progressive Web App) ZIP processing endpoint (POST /api/pwa/process-zip) allows an authenticated user with builder privileges to read arbitrary ",
    }
