"""
Detection: Authentication with Entra ID
Category: auth
Severity: INFO
MITRE: N/A
Source: https://www.reddit.com/r/aws/comments/1rshukj/authentication_with_entra_id/

Auto-generated by cloud-sec-blog detection pipeline.
Compatible with: https://github.com/jackiecloudsec/detection-as-code
"""

import json
import logging

log = logging.getLogger(__name__)

# Detection metadata
DETECTION_ID = "reddit-1rshukj"
DETECTION_NAME = "Authentication with Entra ID"
DETECTION_SEVERITY = "info"
MITRE_TTPS = []
CLOUDTRAIL_EVENTS = ['AuthorizeSecurityGroupIngress', 'ConsoleLogin', 'CreateAccessKey', 'CreateSecurityGroup', 'CreateVpc', 'DescribeInstances', 'DescribeSecurityGroups', 'GetFederationToken', 'GetSecretValue', 'ModifyInstanceAttribute', 'ModifyVpcAttribute', 'RunInstances', 'StartInstances', 'StopInstances', 'TerminateInstances']


def logql_query() -> str:
    """LogQL query for Loki to pull relevant CloudTrail events."""
    return '{job="cloudtrail"} |~ `"eventName":"(AuthorizeSecurityGroupIngress|ConsoleLogin|CreateAccessKey|CreateSecurityGroup|CreateVpc|DescribeInstances|DescribeSecurityGroups|GetFederationToken|GetSecretValue|ModifyInstanceAttribute)"`'


def detect(event: dict) -> bool:
    """
    Evaluate whether a CloudTrail event matches this detection.

    Args:
        event: parsed CloudTrail event dict

    Returns:
        True if the event should trigger an alert
    """
    try:
        event_name = event.get('eventName', '')
        return event_name in ("AuthorizeSecurityGroupIngress", "ConsoleLogin", "CreateAccessKey", "CreateSecurityGroup", "CreateVpc", "DescribeInstances", "DescribeSecurityGroups", "GetFederationToken", "GetSecretValue", "ModifyInstanceAttribute",)
    except Exception as e:
        log.warning(f"Detection error in {DETECTION_ID}: {e}")
        return False


def title(event: dict) -> str:
    """Generate alert title with event context."""
    user = event.get("userIdentity", {}).get("arn", "unknown")
    event_name = event.get("eventName", "unknown")
    return f"{DETECTION_NAME} — {event_name} by {user}"


def severity(event: dict) -> str:
    """Return severity level. Can be dynamic based on event context."""
    error_code = event.get("errorCode")
    if error_code:
        return "low"  # failed attempt is lower priority
    return DETECTION_SEVERITY


def runbook(event: dict) -> str:
    """Return remediation steps for responders."""
    return "1. Review the CloudTrail event in the alert context\n2. Identify the IAM principal (userIdentity.arn) and source IP\n3. Determine if the activity is authorized\n4. If unauthorized: disable the IAM user/key immediately\n5. Rotate any exposed credentials\n7. Threat intel source: https://www.reddit.com/r/aws/comments/1rshukj/authentication_with_entra_id/"


def metadata() -> dict:
    """Return detection metadata for the engine registry."""
    return {
        "id": DETECTION_ID,
        "name": DETECTION_NAME,
        "severity": DETECTION_SEVERITY,
        "mitre_ttps": MITRE_TTPS,
        "cloudtrail_events": CLOUDTRAIL_EVENTS,
        "category": "auth",
        "description": "We are trying to move away from Fleet Manager. The idea is to be able to connect to EC2 instances via RDP and SSH using the existing Microsoft Entra credentials. What solutions are people using for this scenario? We already have network connectivity to the instances, so that's sorted. We are also tr",
    }
