"""
Detection: AWS IAM Identity Center Applications - preferably with Terraform
Category: auth
Severity: INFO
MITRE: N/A
Source: https://www.reddit.com/r/aws/comments/1rrq3q3/aws_iam_identity_center_applications_preferably/

Auto-generated by cloud-sec-blog detection pipeline.
Compatible with: https://github.com/jackiecloudsec/detection-as-code
"""

import json
import logging

log = logging.getLogger(__name__)

# Detection metadata
DETECTION_ID = "reddit-1rrq3q3"
DETECTION_NAME = "AWS IAM Identity Center Applications - preferably with Terraform"
DETECTION_SEVERITY = "info"
MITRE_TTPS = []
CLOUDTRAIL_EVENTS = ['AddUserToGroup', 'AssumeRoleWithSAML', 'AttachRolePolicy', 'AttachUserPolicy', 'CreateAccessKey', 'CreateAccountAssignment', 'CreateChangeSet', 'CreateLoginProfile', 'CreatePermissionSet', 'CreateRole', 'CreateStack', 'CreateUser', 'DeleteStack', 'DeleteUser', 'PutUserPolicy']


def logql_query() -> str:
    """LogQL query for Loki to pull relevant CloudTrail events."""
    return '{job="cloudtrail"} |~ `"eventName":"(AddUserToGroup|AssumeRoleWithSAML|AttachRolePolicy|AttachUserPolicy|CreateAccessKey|CreateAccountAssignment|CreateChangeSet|CreateLoginProfile|CreatePermissionSet|CreateRole)"`'


def detect(event: dict) -> bool:
    """
    Evaluate whether a CloudTrail event matches this detection.

    Args:
        event: parsed CloudTrail event dict

    Returns:
        True if the event should trigger an alert
    """
    try:
        event_name = event.get('eventName', '')
        return event_name in ("AddUserToGroup", "AssumeRoleWithSAML", "AttachRolePolicy", "AttachUserPolicy", "CreateAccessKey", "CreateAccountAssignment", "CreateChangeSet", "CreateLoginProfile", "CreatePermissionSet", "CreateRole",)
    except Exception as e:
        log.warning(f"Detection error in {DETECTION_ID}: {e}")
        return False


def title(event: dict) -> str:
    """Generate alert title with event context."""
    user = event.get("userIdentity", {}).get("arn", "unknown")
    event_name = event.get("eventName", "unknown")
    return f"{DETECTION_NAME} — {event_name} by {user}"


def severity(event: dict) -> str:
    """Return severity level. Can be dynamic based on event context."""
    error_code = event.get("errorCode")
    if error_code:
        return "low"  # failed attempt is lower priority
    return DETECTION_SEVERITY


def runbook(event: dict) -> str:
    """Return remediation steps for responders."""
    return "1. Review the CloudTrail event in the alert context\n2. Identify the IAM principal (userIdentity.arn) and source IP\n3. Determine if the activity is authorized\n4. If unauthorized: disable the IAM user/key immediately\n5. Rotate any exposed credentials\n7. Threat intel source: https://www.reddit.com/r/aws/comments/1rrq3q3/aws_iam_identity_center_applications_preferably/"


def metadata() -> dict:
    """Return detection metadata for the engine registry."""
    return {
        "id": DETECTION_ID,
        "name": DETECTION_NAME,
        "severity": DETECTION_SEVERITY,
        "mitre_ttps": MITRE_TTPS,
        "cloudtrail_events": CLOUDTRAIL_EVENTS,
        "category": "auth",
        "description": "I am trying to create an application that I want to make available via the standard AWS SSO start page.  I am deploying with Terraform, but i appreciate there are a few things Terraform doesnt yet support, so open to Cloudformation or CLI commands if necessary.     The app is a React SPA, stored in",
    }
