"""
Detection: Storm-2561 Spreads Trojan VPN Clients via SEO Poisoning to Steal Credentials
Category: auth
Severity: INFO
MITRE: N/A
Source: https://thehackernews.com/2026/03/storm-2561-spreads-trojan-vpn-clients.html

Auto-generated by cloud-sec-blog detection pipeline.
Compatible with: https://github.com/jackiecloudsec/detection-as-code
"""

import json
import logging

log = logging.getLogger(__name__)

# Detection metadata
DETECTION_ID = "rss-thehackernews-storm-2561-spreads-trojan-vpn-clients-via-seo-poisoning-to-s"
DETECTION_NAME = "Storm-2561 Spreads Trojan VPN Clients via SEO Poisoning to Steal Credentials"
DETECTION_SEVERITY = "info"
MITRE_TTPS = []
CLOUDTRAIL_EVENTS = ['AuthorizeSecurityGroupIngress', 'ConsoleLogin', 'CreateAccessKey', 'CreateVpc', 'GetFederationToken', 'GetSecretValue', 'ModifyVpcAttribute']


def logql_query() -> str:
    """LogQL query for Loki to pull relevant CloudTrail events."""
    return '{job="cloudtrail"} |~ `"eventName":"(AuthorizeSecurityGroupIngress|ConsoleLogin|CreateAccessKey|CreateVpc|GetFederationToken|GetSecretValue|ModifyVpcAttribute)"`'


def detect(event: dict) -> bool:
    """
    Evaluate whether a CloudTrail event matches this detection.

    Args:
        event: parsed CloudTrail event dict

    Returns:
        True if the event should trigger an alert
    """
    try:
        event_name = event.get('eventName', '')
        return event_name in ("AuthorizeSecurityGroupIngress", "ConsoleLogin", "CreateAccessKey", "CreateVpc", "GetFederationToken", "GetSecretValue", "ModifyVpcAttribute",)
    except Exception as e:
        log.warning(f"Detection error in {DETECTION_ID}: {e}")
        return False


def title(event: dict) -> str:
    """Generate alert title with event context."""
    user = event.get("userIdentity", {}).get("arn", "unknown")
    event_name = event.get("eventName", "unknown")
    return f"{DETECTION_NAME} — {event_name} by {user}"


def severity(event: dict) -> str:
    """Return severity level. Can be dynamic based on event context."""
    error_code = event.get("errorCode")
    if error_code:
        return "low"  # failed attempt is lower priority
    return DETECTION_SEVERITY


def runbook(event: dict) -> str:
    """Return remediation steps for responders."""
    return "1. Review the CloudTrail event in the alert context\n2. Identify the IAM principal (userIdentity.arn) and source IP\n3. Determine if the activity is authorized\n4. If unauthorized: disable the IAM user/key immediately\n5. Rotate any exposed credentials\n7. Threat intel source: https://thehackernews.com/2026/03/storm-2561-spreads-trojan-vpn-clients.html"


def metadata() -> dict:
    """Return detection metadata for the engine registry."""
    return {
        "id": DETECTION_ID,
        "name": DETECTION_NAME,
        "severity": DETECTION_SEVERITY,
        "mitre_ttps": MITRE_TTPS,
        "cloudtrail_events": CLOUDTRAIL_EVENTS,
        "category": "auth",
        "description": "Microsoft has disclosed details of a credential theft campaign that employs fake virtual private network (VPN) clients distributed through search engine optimization (SEO) poisoning techniques. \"The campaign redirects users searching for legitimate enterprise software to malicious ZIP files on attac",
    }
