"""
Detection: Microsoft Patches 84 Flaws in March Patch Tuesday, Including Two Public Zero-Day
Category: auth
Severity: INFO
MITRE: N/A
Source: https://thehackernews.com/2026/03/microsoft-patches-84-flaws-in-march.html

Auto-generated by cloud-sec-blog detection pipeline.
Compatible with: https://github.com/jackiecloudsec/detection-as-code
"""

import json
import logging

log = logging.getLogger(__name__)

# Detection metadata
DETECTION_ID = "rss-thehackernews-microsoft-patches-84-flaws-in-march-patch-tuesday-including"
DETECTION_NAME = "Microsoft Patches 84 Flaws in March Patch Tuesday, Including Two Public Zero-Day"
DETECTION_SEVERITY = "info"
MITRE_TTPS = []
CLOUDTRAIL_EVENTS = ['AttachGroupPolicy', 'AttachRolePolicy', 'AttachUserPolicy', 'CreatePolicyVersion', 'PutRolePolicy', 'PutUserPolicy', 'SetDefaultPolicyVersion']


def logql_query() -> str:
    """LogQL query for Loki to pull relevant CloudTrail events."""
    return '{job="cloudtrail"} |~ `"eventName":"(AttachGroupPolicy|AttachRolePolicy|AttachUserPolicy|CreatePolicyVersion|PutRolePolicy|PutUserPolicy|SetDefaultPolicyVersion)"`'


def detect(event: dict) -> bool:
    """
    Evaluate whether a CloudTrail event matches this detection.

    Args:
        event: parsed CloudTrail event dict

    Returns:
        True if the event should trigger an alert
    """
    try:
        event_name = event.get('eventName', '')
        return event_name in ("AttachGroupPolicy", "AttachRolePolicy", "AttachUserPolicy", "CreatePolicyVersion", "PutRolePolicy", "PutUserPolicy", "SetDefaultPolicyVersion",)
    except Exception as e:
        log.warning(f"Detection error in {DETECTION_ID}: {e}")
        return False


def title(event: dict) -> str:
    """Generate alert title with event context."""
    user = event.get("userIdentity", {}).get("arn", "unknown")
    event_name = event.get("eventName", "unknown")
    return f"{DETECTION_NAME} — {event_name} by {user}"


def severity(event: dict) -> str:
    """Return severity level. Can be dynamic based on event context."""
    error_code = event.get("errorCode")
    if error_code:
        return "low"  # failed attempt is lower priority
    return DETECTION_SEVERITY


def runbook(event: dict) -> str:
    """Return remediation steps for responders."""
    return "1. Review the CloudTrail event in the alert context\n2. Identify the IAM principal (userIdentity.arn) and source IP\n3. Determine if the activity is authorized\n4. If unauthorized: disable the IAM user/key immediately\n5. Rotate any exposed credentials\n7. Threat intel source: https://thehackernews.com/2026/03/microsoft-patches-84-flaws-in-march.html"


def metadata() -> dict:
    """Return detection metadata for the engine registry."""
    return {
        "id": DETECTION_ID,
        "name": DETECTION_NAME,
        "severity": DETECTION_SEVERITY,
        "mitre_ttps": MITRE_TTPS,
        "cloudtrail_events": CLOUDTRAIL_EVENTS,
        "category": "auth",
        "description": "Microsoft on Tuesday released patches for a set of 84 new security vulnerabilities affecting various software components, including two that have been listed as publicly known. Of these, eight are rated Critical, and 76 are rated Important in severity. Forty-six of the patched vulnerabilities relate",
    }
