"""
Detection: How AI Assistants are Moving the Security Goalposts
Category: auth
Severity: INFO
MITRE: N/A
Source: https://krebsonsecurity.com/2026/03/how-ai-assistants-are-moving-the-security-goalposts/

Auto-generated by cloud-sec-blog detection pipeline.
Compatible with: https://github.com/jackiecloudsec/detection-as-code
"""

import json
import logging

log = logging.getLogger(__name__)

# Detection metadata
DETECTION_ID = "rss-krebsonsecurity-how-ai-assistants-are-moving-the-security-goalposts"
DETECTION_NAME = "How AI Assistants are Moving the Security Goalposts"
DETECTION_SEVERITY = "info"
MITRE_TTPS = []
CLOUDTRAIL_EVENTS = ['AssumeRole', 'AssumeRoleWithSAML', 'CreateAccount', 'CreateCluster', 'CreateNodegroup', 'GetCallerIdentity', 'GetFederationToken', 'InviteAccountToOrganization', 'LeaveOrganization', 'UpdateClusterConfig']


def logql_query() -> str:
    """LogQL query for Loki to pull relevant CloudTrail events."""
    return '{job="cloudtrail"} |~ `"eventName":"(AssumeRole|AssumeRoleWithSAML|CreateAccount|CreateCluster|CreateNodegroup|GetCallerIdentity|GetFederationToken|InviteAccountToOrganization|LeaveOrganization|UpdateClusterConfig)"`'


def detect(event: dict) -> bool:
    """
    Evaluate whether a CloudTrail event matches this detection.

    Args:
        event: parsed CloudTrail event dict

    Returns:
        True if the event should trigger an alert
    """
    try:
        event_name = event.get('eventName', '')
        return event_name in ("AssumeRole", "AssumeRoleWithSAML", "CreateAccount", "CreateCluster", "CreateNodegroup", "GetCallerIdentity", "GetFederationToken", "InviteAccountToOrganization", "LeaveOrganization", "UpdateClusterConfig",)
    except Exception as e:
        log.warning(f"Detection error in {DETECTION_ID}: {e}")
        return False


def title(event: dict) -> str:
    """Generate alert title with event context."""
    user = event.get("userIdentity", {}).get("arn", "unknown")
    event_name = event.get("eventName", "unknown")
    return f"{DETECTION_NAME} — {event_name} by {user}"


def severity(event: dict) -> str:
    """Return severity level. Can be dynamic based on event context."""
    error_code = event.get("errorCode")
    if error_code:
        return "low"  # failed attempt is lower priority
    return DETECTION_SEVERITY


def runbook(event: dict) -> str:
    """Return remediation steps for responders."""
    return "1. Review the CloudTrail event in the alert context\n2. Identify the IAM principal (userIdentity.arn) and source IP\n3. Determine if the activity is authorized\n4. If unauthorized: contain the affected resource\n5. Preserve CloudTrail logs for forensic analysis\n7. Threat intel source: https://krebsonsecurity.com/2026/03/how-ai-assistants-are-moving-the-security-goalposts/"


def metadata() -> dict:
    """Return detection metadata for the engine registry."""
    return {
        "id": DETECTION_ID,
        "name": DETECTION_NAME,
        "severity": DETECTION_SEVERITY,
        "mitre_ttps": MITRE_TTPS,
        "cloudtrail_events": CLOUDTRAIL_EVENTS,
        "category": "auth",
        "description": "AI-based assistants or \"agents\" -- autonomous programs that have access to the user's computer, files, online services and can automate virtually any task -- are growing in popularity with developers and IT workers. But as so many eyebrow-raising headlines over the past few weeks have shown, these p",
    }
