"""
Detection: Deploy AWS applications and access AWS accounts across multiple Regions with IAM
Category: auth
Severity: INFO
MITRE: N/A
Source: https://aws.amazon.com/blogs/security/deploy-aws-applications-and-access-aws-accounts-across-multiple-regions-with-iam-identity-center/

Auto-generated by cloud-sec-blog detection pipeline.
Compatible with: https://github.com/jackiecloudsec/detection-as-code
"""

import json
import logging

log = logging.getLogger(__name__)

# Detection metadata
DETECTION_ID = "rss-awssecurityblog-deploy-aws-applications-and-access-aws-accounts-across-multi"
DETECTION_NAME = "Deploy AWS applications and access AWS accounts across multiple Regions with IAM"
DETECTION_SEVERITY = "info"
MITRE_TTPS = []
CLOUDTRAIL_EVENTS = ['AddUserToGroup', 'AttachRolePolicy', 'AttachUserPolicy', 'CreateAccessKey', 'CreateAccount', 'CreateLoginProfile', 'CreateRole', 'CreateUser', 'DeleteUser', 'InviteAccountToOrganization', 'LeaveOrganization', 'PutUserPolicy', 'UpdateLoginProfile']


def logql_query() -> str:
    """LogQL query for Loki to pull relevant CloudTrail events."""
    return '{job="cloudtrail"} |~ `"eventName":"(AddUserToGroup|AttachRolePolicy|AttachUserPolicy|CreateAccessKey|CreateAccount|CreateLoginProfile|CreateRole|CreateUser|DeleteUser|InviteAccountToOrganization)"`'


def detect(event: dict) -> bool:
    """
    Evaluate whether a CloudTrail event matches this detection.

    Args:
        event: parsed CloudTrail event dict

    Returns:
        True if the event should trigger an alert
    """
    try:
        event_name = event.get('eventName', '')
        return event_name in ("AddUserToGroup", "AttachRolePolicy", "AttachUserPolicy", "CreateAccessKey", "CreateAccount", "CreateLoginProfile", "CreateRole", "CreateUser", "DeleteUser", "InviteAccountToOrganization",)
    except Exception as e:
        log.warning(f"Detection error in {DETECTION_ID}: {e}")
        return False


def title(event: dict) -> str:
    """Generate alert title with event context."""
    user = event.get("userIdentity", {}).get("arn", "unknown")
    event_name = event.get("eventName", "unknown")
    return f"{DETECTION_NAME} — {event_name} by {user}"


def severity(event: dict) -> str:
    """Return severity level. Can be dynamic based on event context."""
    error_code = event.get("errorCode")
    if error_code:
        return "low"  # failed attempt is lower priority
    return DETECTION_SEVERITY


def runbook(event: dict) -> str:
    """Return remediation steps for responders."""
    return "1. Review the CloudTrail event in the alert context\n2. Identify the IAM principal (userIdentity.arn) and source IP\n3. Determine if the activity is authorized\n4. If unauthorized: disable the IAM user/key immediately\n5. Rotate any exposed credentials\n7. Threat intel source: https://aws.amazon.com/blogs/security/deploy-aws-applications-and-access-aws-accounts-across-multiple-regions-with-iam-identity-center/"


def metadata() -> dict:
    """Return detection metadata for the engine registry."""
    return {
        "id": DETECTION_ID,
        "name": DETECTION_NAME,
        "severity": DETECTION_SEVERITY,
        "mitre_ttps": MITRE_TTPS,
        "cloudtrail_events": CLOUDTRAIL_EVENTS,
        "category": "auth",
        "description": "If your organization relies on AWS IAM Identity Center for workforce access, you can now extend that access across multiple AWS Regions with multi-Region replication. Previously, AWS access portal was only available in one Region, when you add an additional Region, users get an active access portal ",
    }
