"""
Detection: A React-based phishing page with credential exfiltration via EmailJS, (Fri, Mar 
Category: auth
Severity: INFO
MITRE: N/A
Source: https://isc.sans.edu/diary/rss/32794

Auto-generated by cloud-sec-blog detection pipeline.
Compatible with: https://github.com/jackiecloudsec/detection-as-code
"""

import json
import logging

log = logging.getLogger(__name__)

# Detection metadata
DETECTION_ID = "rss-sansinternetstormcenter-a-react-based-phishing-page-with-credential-exfiltration-via"
DETECTION_NAME = "A React-based phishing page with credential exfiltration via EmailJS, (Fri, Mar "
DETECTION_SEVERITY = "info"
MITRE_TTPS = []
CLOUDTRAIL_EVENTS = ['ConsoleLogin', 'CreateAccessKey', 'CreateImage', 'DeregisterImage', 'DescribeImages', 'GetFederationToken', 'GetSecretValue', 'ModifyImageAttribute']


def logql_query() -> str:
    """LogQL query for Loki to pull relevant CloudTrail events."""
    return '{job="cloudtrail"} |~ `"eventName":"(ConsoleLogin|CreateAccessKey|CreateImage|DeregisterImage|DescribeImages|GetFederationToken|GetSecretValue|ModifyImageAttribute)"`'


def detect(event: dict) -> bool:
    """
    Evaluate whether a CloudTrail event matches this detection.

    Args:
        event: parsed CloudTrail event dict

    Returns:
        True if the event should trigger an alert
    """
    try:
        event_name = event.get('eventName', '')
        return event_name in ("ConsoleLogin", "CreateAccessKey", "CreateImage", "DeregisterImage", "DescribeImages", "GetFederationToken", "GetSecretValue", "ModifyImageAttribute",)
    except Exception as e:
        log.warning(f"Detection error in {DETECTION_ID}: {e}")
        return False


def title(event: dict) -> str:
    """Generate alert title with event context."""
    user = event.get("userIdentity", {}).get("arn", "unknown")
    event_name = event.get("eventName", "unknown")
    return f"{DETECTION_NAME} — {event_name} by {user}"


def severity(event: dict) -> str:
    """Return severity level. Can be dynamic based on event context."""
    error_code = event.get("errorCode")
    if error_code:
        return "low"  # failed attempt is lower priority
    return DETECTION_SEVERITY


def runbook(event: dict) -> str:
    """Return remediation steps for responders."""
    return "1. Review the CloudTrail event in the alert context\n2. Identify the IAM principal (userIdentity.arn) and source IP\n3. Determine if the activity is authorized\n4. If unauthorized: disable the IAM user/key immediately\n5. Rotate any exposed credentials\n7. Threat intel source: https://isc.sans.edu/diary/rss/32794"


def metadata() -> dict:
    """Return detection metadata for the engine registry."""
    return {
        "id": DETECTION_ID,
        "name": DETECTION_NAME,
        "severity": DETECTION_SEVERITY,
        "mitre_ttps": MITRE_TTPS,
        "cloudtrail_events": CLOUDTRAIL_EVENTS,
        "category": "auth",
        "description": "On Wednesday, a phishing message made its way into our handler inbox that contained a fairly typical low-quality lure, but turned out to be quite interesting in the end nonetheless. That is because the accompanying credential stealing web page was dynamically constructed using React and used a legit",
    }
