"""
Detection: T1610 — Deploy Container
Category: network
Severity: INFO
MITRE: T1610
Source: https://attack.mitre.org/techniques/T1610

Auto-generated by cloud-sec-blog detection pipeline.
Compatible with: https://github.com/jackiecloudsec/detection-as-code
"""

import json
import logging

log = logging.getLogger(__name__)

# Detection metadata
DETECTION_ID = "attack-T1610"
DETECTION_NAME = "T1610 — Deploy Container"
DETECTION_SEVERITY = "info"
MITRE_TTPS = ['T1610']
CLOUDTRAIL_EVENTS = ['AssumeRoleWithSAML', 'AuthorizeSecurityGroupIngress', 'CreateAccountAssignment', 'CreateCluster', 'CreateNodegroup', 'CreatePermissionSet', 'CreateVpc', 'DeleteConfigurationRecorder', 'DeleteDeliveryChannel', 'ModifyVpcAttribute', 'RegisterTaskDefinition', 'RunTask', 'StopConfigurationRecorder']


def logql_query() -> str:
    """LogQL query for Loki to pull relevant CloudTrail events."""
    return '{job="cloudtrail"} |~ `"eventName":"(AssumeRoleWithSAML|AuthorizeSecurityGroupIngress|CreateAccountAssignment|CreateCluster|CreateNodegroup|CreatePermissionSet|CreateVpc|DeleteConfigurationRecorder|DeleteDeliveryChannel|ModifyVpcAttribute)"`'


def detect(event: dict) -> bool:
    """
    Evaluate whether a CloudTrail event matches this detection.

    Args:
        event: parsed CloudTrail event dict

    Returns:
        True if the event should trigger an alert
    """
    try:
        event_name = event.get('eventName', '')
        return event_name in ("AssumeRoleWithSAML", "AuthorizeSecurityGroupIngress", "CreateAccountAssignment", "CreateCluster", "CreateNodegroup", "CreatePermissionSet", "CreateVpc", "DeleteConfigurationRecorder", "DeleteDeliveryChannel", "ModifyVpcAttribute",)
    except Exception as e:
        log.warning(f"Detection error in {DETECTION_ID}: {e}")
        return False


def title(event: dict) -> str:
    """Generate alert title with event context."""
    user = event.get("userIdentity", {}).get("arn", "unknown")
    event_name = event.get("eventName", "unknown")
    return f"{DETECTION_NAME} — {event_name} by {user}"


def severity(event: dict) -> str:
    """Return severity level. Can be dynamic based on event context."""
    error_code = event.get("errorCode")
    if error_code:
        return "low"  # failed attempt is lower priority
    return DETECTION_SEVERITY


def runbook(event: dict) -> str:
    """Return remediation steps for responders."""
    return "1. Review the CloudTrail event in the alert context\n2. Identify the IAM principal (userIdentity.arn) and source IP\n3. Determine if the activity is authorized\n4. If unauthorized: contain the affected resource\n5. Preserve CloudTrail logs for forensic analysis\n6. MITRE ATT&CK reference: T1610\n7. Threat intel source: https://attack.mitre.org/techniques/T1610"


def metadata() -> dict:
    """Return detection metadata for the engine registry."""
    return {
        "id": DETECTION_ID,
        "name": DETECTION_NAME,
        "severity": DETECTION_SEVERITY,
        "mitre_ttps": MITRE_TTPS,
        "cloudtrail_events": CLOUDTRAIL_EVENTS,
        "category": "network",
        "description": "Adversaries may deploy a container into an environment to facilitate execution or evade defenses. In some cases, adversaries may deploy a new container to execute processes associated with a particular image or deployment, such as processes that execute or download malware. In others, an adversary m",
    }
