"""
Detection: T1562.007 — Disable or Modify Cloud Firewall
Category: network
Severity: INFO
MITRE: T1562.007
Source: https://attack.mitre.org/techniques/T1562/007

Auto-generated by cloud-sec-blog detection pipeline.
Compatible with: https://github.com/jackiecloudsec/detection-as-code
"""

import json
import logging

log = logging.getLogger(__name__)

# Detection metadata
DETECTION_ID = "attack-T1562.007"
DETECTION_NAME = "T1562.007 — Disable or Modify Cloud Firewall"
DETECTION_SEVERITY = "info"
MITRE_TTPS = ['T1562.007']
CLOUDTRAIL_EVENTS = ['StopLogging', 'DeleteTrail', 'UpdateTrail', 'DisableRule', 'DeleteDetector', 'UpdateDetector']


def logql_query() -> str:
    """LogQL query for Loki to pull relevant CloudTrail events."""
    return '{job="cloudtrail"} |~ `"eventName":"(StopLogging|DeleteTrail|UpdateTrail|DisableRule|DeleteDetector|UpdateDetector)"`'


def detect(event: dict) -> bool:
    """
    Evaluate whether a CloudTrail event matches this detection.

    Args:
        event: parsed CloudTrail event dict

    Returns:
        True if the event should trigger an alert
    """
    try:
        event_name = event.get('eventName', '')
        return event_name in ("StopLogging", "DeleteTrail", "UpdateTrail", "DisableRule", "DeleteDetector", "UpdateDetector",)
    except Exception as e:
        log.warning(f"Detection error in {DETECTION_ID}: {e}")
        return False


def title(event: dict) -> str:
    """Generate alert title with event context."""
    user = event.get("userIdentity", {}).get("arn", "unknown")
    event_name = event.get("eventName", "unknown")
    return f"{DETECTION_NAME} — {event_name} by {user}"


def severity(event: dict) -> str:
    """Return severity level. Can be dynamic based on event context."""
    error_code = event.get("errorCode")
    if error_code:
        return "low"  # failed attempt is lower priority
    return DETECTION_SEVERITY


def runbook(event: dict) -> str:
    """Return remediation steps for responders."""
    return "1. Review the CloudTrail event in the alert context\n2. Identify the IAM principal (userIdentity.arn) and source IP\n3. Determine if the activity is authorized\n4. Re-enable CloudTrail logging immediately\n5. This is a high-priority evasion indicator — escalate\n6. MITRE ATT&CK reference: T1562.007\n7. Threat intel source: https://attack.mitre.org/techniques/T1562/007"


def metadata() -> dict:
    """Return detection metadata for the engine registry."""
    return {
        "id": DETECTION_ID,
        "name": DETECTION_NAME,
        "severity": DETECTION_SEVERITY,
        "mitre_ttps": MITRE_TTPS,
        "cloudtrail_events": CLOUDTRAIL_EVENTS,
        "category": "network",
        "description": "Adversaries may disable or modify a firewall within a cloud environment to bypass controls that limit access to cloud resources. Cloud firewalls are separate from system firewalls that are described in [Disable or Modify System Firewall](https://attack.mitre.org/techniques/T1562/004).   Cloud enviro",
    }
