"""
Detection: Active C2: Emotet botnet (1 IPs)
Category: network
Severity: HIGH
MITRE: T1071.001, T1095
Source: https://feodotracker.abuse.ch

Auto-generated by cloud-sec-blog detection pipeline.
Compatible with: https://github.com/jackiecloudsec/detection-as-code
"""

import json
import logging

log = logging.getLogger(__name__)

# Detection metadata
DETECTION_ID = "feodo-emotet"
DETECTION_NAME = "Active C2: Emotet botnet (1 IPs)"
DETECTION_SEVERITY = "high"
MITRE_TTPS = ['T1071.001', 'T1095']
CLOUDTRAIL_EVENTS = ['AuthorizeSecurityGroupEgress', 'AuthorizeSecurityGroupIngress', 'CreateSecurityGroup', 'CreateVpc', 'DeleteVpc', 'DescribeVpcs', 'ModifyVpcAttribute', 'RevokeSecurityGroupIngress']


def logql_query() -> str:
    """LogQL query for Loki to pull relevant CloudTrail events."""
    return '{job="cloudtrail"} |~ `"eventName":"(AuthorizeSecurityGroupEgress|AuthorizeSecurityGroupIngress|CreateSecurityGroup|CreateVpc|DeleteVpc|DescribeVpcs|ModifyVpcAttribute|RevokeSecurityGroupIngress)"`'


def detect(event: dict) -> bool:
    """
    Evaluate whether a CloudTrail event matches this detection.

    Args:
        event: parsed CloudTrail event dict

    Returns:
        True if the event should trigger an alert
    """
    try:
        event_name = event.get('eventName', '')
        return event_name in ("AuthorizeSecurityGroupEgress", "AuthorizeSecurityGroupIngress", "CreateSecurityGroup", "CreateVpc", "DeleteVpc", "DescribeVpcs", "ModifyVpcAttribute", "RevokeSecurityGroupIngress",)
    except Exception as e:
        log.warning(f"Detection error in {DETECTION_ID}: {e}")
        return False


def title(event: dict) -> str:
    """Generate alert title with event context."""
    user = event.get("userIdentity", {}).get("arn", "unknown")
    event_name = event.get("eventName", "unknown")
    return f"{DETECTION_NAME} — {event_name} by {user}"


def severity(event: dict) -> str:
    """Return severity level. Can be dynamic based on event context."""
    error_code = event.get("errorCode")
    if error_code:
        return "low"  # failed attempt is lower priority
    return DETECTION_SEVERITY


def runbook(event: dict) -> str:
    """Return remediation steps for responders."""
    return "1. Review the CloudTrail event in the alert context\n2. Identify the IAM principal (userIdentity.arn) and source IP\n3. Determine if the activity is authorized\n4. If unauthorized: contain the affected resource\n5. Preserve CloudTrail logs for forensic analysis\n6. MITRE ATT&CK reference: T1071.001, T1095\n7. Threat intel source: https://feodotracker.abuse.ch"


def metadata() -> dict:
    """Return detection metadata for the engine registry."""
    return {
        "id": DETECTION_ID,
        "name": DETECTION_NAME,
        "severity": DETECTION_SEVERITY,
        "mitre_ttps": MITRE_TTPS,
        "cloudtrail_events": CLOUDTRAIL_EVENTS,
        "category": "network",
        "description": "Active Emotet botnet C2 infrastructure. 1 IPs on port(s) 8080. Block in VPC Security Groups and NACLs. Hunt for connections in VPC Flow Logs.",
    }
