"""
Detection: OpenClaw AI Agent Flaws Could Enable Prompt Injection and Data Exfiltration
Category: network
Severity: INFO
MITRE: N/A
Source: https://thehackernews.com/2026/03/openclaw-ai-agent-flaws-could-enable.html

Auto-generated by cloud-sec-blog detection pipeline.
Compatible with: https://github.com/jackiecloudsec/detection-as-code
"""

import json
import logging

log = logging.getLogger(__name__)

# Detection metadata
DETECTION_ID = "rss-thehackernews-openclaw-ai-agent-flaws-could-enable-prompt-injection-and-da"
DETECTION_NAME = "OpenClaw AI Agent Flaws Could Enable Prompt Injection and Data Exfiltration"
DETECTION_SEVERITY = "info"
MITRE_TTPS = []
CLOUDTRAIL_EVENTS = ['AuthorizeSecurityGroupIngress', 'CopyObject', 'CopySnapshot', 'CreateSnapshot', 'CreateVpc', 'DeleteConfigurationRecorder', 'DeleteDeliveryChannel', 'GetObject', 'ModifyVpcAttribute', 'PutBucketAcl', 'PutBucketPolicy', 'StopConfigurationRecorder']


def logql_query() -> str:
    """LogQL query for Loki to pull relevant CloudTrail events."""
    return '{job="cloudtrail"} |~ `"eventName":"(AuthorizeSecurityGroupIngress|CopyObject|CopySnapshot|CreateSnapshot|CreateVpc|DeleteConfigurationRecorder|DeleteDeliveryChannel|GetObject|ModifyVpcAttribute|PutBucketAcl)"`'


def detect(event: dict) -> bool:
    """
    Evaluate whether a CloudTrail event matches this detection.

    Args:
        event: parsed CloudTrail event dict

    Returns:
        True if the event should trigger an alert
    """
    try:
        event_name = event.get('eventName', '')
        return event_name in ("AuthorizeSecurityGroupIngress", "CopyObject", "CopySnapshot", "CreateSnapshot", "CreateVpc", "DeleteConfigurationRecorder", "DeleteDeliveryChannel", "GetObject", "ModifyVpcAttribute", "PutBucketAcl",)
    except Exception as e:
        log.warning(f"Detection error in {DETECTION_ID}: {e}")
        return False


def title(event: dict) -> str:
    """Generate alert title with event context."""
    user = event.get("userIdentity", {}).get("arn", "unknown")
    event_name = event.get("eventName", "unknown")
    return f"{DETECTION_NAME} — {event_name} by {user}"


def severity(event: dict) -> str:
    """Return severity level. Can be dynamic based on event context."""
    error_code = event.get("errorCode")
    if error_code:
        return "low"  # failed attempt is lower priority
    return DETECTION_SEVERITY


def runbook(event: dict) -> str:
    """Return remediation steps for responders."""
    return "1. Review the CloudTrail event in the alert context\n2. Identify the IAM principal (userIdentity.arn) and source IP\n3. Determine if the activity is authorized\n4. If unauthorized: revert bucket policy and enable Block Public Access\n5. Check for data exfiltration in S3 server access logs\n7. Threat intel source: https://thehackernews.com/2026/03/openclaw-ai-agent-flaws-could-enable.html"


def metadata() -> dict:
    """Return detection metadata for the engine registry."""
    return {
        "id": DETECTION_ID,
        "name": DETECTION_NAME,
        "severity": DETECTION_SEVERITY,
        "mitre_ttps": MITRE_TTPS,
        "cloudtrail_events": CLOUDTRAIL_EVENTS,
        "category": "network",
        "description": "China's National Computer Network Emergency Response Technical Team (CNCERT) has issued a warning about the security stemming from the use of OpenClaw (formerly Clawdbot and Moltbot), an open-source and self-hosted autonomous artificial intelligence (AI) agent. In a post shared on WeChat, CNCERT not",
    }
