"""
Detection: How to manage the lifecycle of Amazon Machine Images using AMI Lineage for AWS
Category: network
Severity: INFO
MITRE: N/A
Source: https://aws.amazon.com/blogs/security/how-to-manage-the-lifecycle-of-amazon-machine-images-using-ami-lineage-for-aws/

Auto-generated by cloud-sec-blog detection pipeline.
Compatible with: https://github.com/jackiecloudsec/detection-as-code
"""

import json
import logging

log = logging.getLogger(__name__)

# Detection metadata
DETECTION_ID = "rss-awssecurityblog-how-to-manage-the-lifecycle-of-amazon-machine-images-using-a"
DETECTION_NAME = "How to manage the lifecycle of Amazon Machine Images using AMI Lineage for AWS"
DETECTION_SEVERITY = "info"
MITRE_TTPS = []
CLOUDTRAIL_EVENTS = ['AuthorizeSecurityGroupIngress', 'CreateAccount', 'CreateImage', 'CreateSecurityGroup', 'DeregisterImage', 'DescribeImages', 'DescribeInstances', 'DescribeSecurityGroups', 'InviteAccountToOrganization', 'LeaveOrganization', 'ModifyImageAttribute', 'ModifyInstanceAttribute', 'RunInstances', 'StartInstances', 'StopInstances']


def logql_query() -> str:
    """LogQL query for Loki to pull relevant CloudTrail events."""
    return '{job="cloudtrail"} |~ `"eventName":"(AuthorizeSecurityGroupIngress|CreateAccount|CreateImage|CreateSecurityGroup|DeregisterImage|DescribeImages|DescribeInstances|DescribeSecurityGroups|InviteAccountToOrganization|LeaveOrganization)"`'


def detect(event: dict) -> bool:
    """
    Evaluate whether a CloudTrail event matches this detection.

    Args:
        event: parsed CloudTrail event dict

    Returns:
        True if the event should trigger an alert
    """
    try:
        event_name = event.get('eventName', '')
        return event_name in ("AuthorizeSecurityGroupIngress", "CreateAccount", "CreateImage", "CreateSecurityGroup", "DeregisterImage", "DescribeImages", "DescribeInstances", "DescribeSecurityGroups", "InviteAccountToOrganization", "LeaveOrganization",)
    except Exception as e:
        log.warning(f"Detection error in {DETECTION_ID}: {e}")
        return False


def title(event: dict) -> str:
    """Generate alert title with event context."""
    user = event.get("userIdentity", {}).get("arn", "unknown")
    event_name = event.get("eventName", "unknown")
    return f"{DETECTION_NAME} — {event_name} by {user}"


def severity(event: dict) -> str:
    """Return severity level. Can be dynamic based on event context."""
    error_code = event.get("errorCode")
    if error_code:
        return "low"  # failed attempt is lower priority
    return DETECTION_SEVERITY


def runbook(event: dict) -> str:
    """Return remediation steps for responders."""
    return "1. Review the CloudTrail event in the alert context\n2. Identify the IAM principal (userIdentity.arn) and source IP\n3. Determine if the activity is authorized\n4. If unauthorized: contain the affected resource\n5. Preserve CloudTrail logs for forensic analysis\n7. Threat intel source: https://aws.amazon.com/blogs/security/how-to-manage-the-lifecycle-of-amazon-machine-images-using-ami-lineage-for-aws/"


def metadata() -> dict:
    """Return detection metadata for the engine registry."""
    return {
        "id": DETECTION_ID,
        "name": DETECTION_NAME,
        "severity": DETECTION_SEVERITY,
        "mitre_ttps": MITRE_TTPS,
        "cloudtrail_events": CLOUDTRAIL_EVENTS,
        "category": "network",
        "description": "As organizations scale their cloud infrastructure, maintaining proper lifecycle management of Amazon Machine Images (AMIs) is a critical component of their security and risk management goals. AMIs provide the essential information required to launch Amazon Elastic Compute Cloud (Amazon EC2) instance",
    }
